// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:271e2774-52d5-4313-bd28-b0dd2e92747c',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'buddyapp-hosting-mobilehub-1821605225',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dknivlv0ccky7.cloudfront.net',
    'aws_mobile_analytics_app_id': 'e2a27d0e517747aa8b21d91599fd182e',
    'aws_project_id': '1dbabbfc-c6c7-4c21-9794-a8c9052b90d7',
    'aws_project_name': 'buddy-app',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'buddyapp-mobilehub-1821605225',
}

export default awsmobile;
