// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_auth_facebook': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:07d04823-d37e-4579-ad24-2a190ef48580',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'buddyapp-hosting-mobilehub-1208719042',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dx53780hgkvkn.cloudfront.net',
    'aws_facebook_app_id': '322887791546157',
    'aws_facebook_app_permissions': 'public_profile',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '4b1412708197402fae4918cc3f3a4353',
    'aws_project_id': 'e5725123-7afc-4dd0-98ee-d50900b5a503',
    'aws_project_name': 'BuddyApp',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'buddyapp-mobilehub-1208719042',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'buddyapp-userfiles-mobilehub-1208719042',
    'aws_user_files_s3_bucket_region': 'us-west-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_4ajxX2UrA',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7fr804avjbru64s9n9ht9bft03',
}

export default awsmobile;
