// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"ejweicgqzh","name":"UserLogsCRUD","description":"","endpoint":"https://ejweicgqzh.execute-api.us-west-1.amazonaws.com/Development","region":"us-west-1","paths":["/logid/{logId}"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:5f8350eb-7c9a-41ed-b437-9d8b421faf0c',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'buddy-hosting-mobilehub-1257947803',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dgqe5unb9vy9s.cloudfront.net',
    'aws_mobile_analytics_app_id': '6343581b8237443a829901b82d540401',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7bb13deb-1519-4d44-870e-280cb5928424',
    'aws_project_name': 'Buddy-2018-01-16-17-59-01',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'buddy-mobilehub-1257947803',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_7WaS5h0h7',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '40jfemo11eoa31f6oijhv9up4v',
}

export default awsmobile;
